#!/usr/bin/env python3
"""Rebuild every Pandoc --reference-doc template from TenX brand
colors/fonts/logo.

Run this whenever colors.md, typography.md, or the logo change. Produces
four reference docs, one per document track, sharing the same fonts/
headings/footer machinery (base_document()) but each with its own
title-page treatment:

  - reference.docx          — policy: restrained, centered, single-focused
    (see build_policy_reference()).
  - reference-document.docx — document: left-aligned, rule-accented,
    living operational/legal records (see build_document_reference()).
  - reference-report.docx   — report: full-bleed graphic cover, the
    "annual report" genre policy deliberately avoids (see
    build_report_reference()).
  - reference-template.docx — template: no title page at all — blank
    fillable forms never trigger Pandoc's title-block (see
    build_template_reference()).

Requires: pandoc, python-docx (`pip install python-docx`).
"""
import subprocess
import tempfile
from pathlib import Path

from docx import Document
from docx.shared import RGBColor, Pt, Cm, Inches
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

REPO_ROOT = Path(__file__).resolve().parent.parent
PANDOC_DIR = Path(__file__).resolve().parent
ASSETS_DIR = PANDOC_DIR / "assets"

PREVIEW_CONTENT_POLICY = PANDOC_DIR / "preview-content.md"
PREVIEW_CONTENT_DOCUMENT = PANDOC_DIR / "preview-content-document.md"
PREVIEW_CONTENT_REPORT = PANDOC_DIR / "preview-content-report.md"
PREVIEW_CONTENT_TEMPLATE = PANDOC_DIR / "preview-content-template.md"

POLICY_OUTPUT = PANDOC_DIR / "reference.docx"
DOCUMENT_OUTPUT = PANDOC_DIR / "reference-document.docx"
REPORT_OUTPUT = PANDOC_DIR / "reference-report.docx"
TEMPLATE_OUTPUT = PANDOC_DIR / "reference-template.docx"

# Stacked lockup (icon above wordmark) for centered compositions (Policy's
# cover, every track's small restrained interior header); horizontal
# lockup (icon beside wordmark) for corner/letterhead placements (Document's
# small header) — a wide lockup reads better in a left-aligned corner than
# a tall stacked one does. The report cover's own white horizontal lockup
# is composited directly onto its mosaic art by generate-cover-art.py, not
# inserted separately here.
LOGO_STACKED_BLACK = REPO_ROOT / "logo" / "png" / "lockup-stacked-black-512.png"
LOGO_HORIZONTAL_BLACK = REPO_ROOT / "logo" / "png" / "lockup-horizontal-black-512.png"
# Generated by generate-cover-art.py — the report cover's masthead
# (mosaic + logo composited together, see that script's docstring for
# the history of what didn't work first).
COVER_ART = ASSETS_DIR / "report-cover-art.png"

ACCENT = RGBColor(0xA8, 0x55, 0xF7)   # colors.md: Accent (violet)
ACCENT_HEX = "A855F7"
GRAY = RGBColor(0x6B, 0x6B, 0x6B)     # colors.md: Gray — mid
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
COVER_HEX = "3D1A5B"                  # colors.md: MASTHEAD_HEX — deep violet, the report cover's background
COVER_LIGHT = RGBColor(0xD8, 0xC9, 0xEE)  # light lavender — secondary text against COVER_HEX
FONT = "Calibri"                      # typography.md

LOGO_HEIGHT = Cm(1.5)              # restrained size shared by every track's non-cover header
POLICY_COVER_LOGO_HEIGHT = Cm(5.0) # policy's title page only — much larger, per direct feedback
REPORT_ART_HEIGHT = Inches(2.7)     # report cover's masthead mosaic (logo already composited onto it — see generate-cover-art.py)

# Cancels the page's 1in left/right margin by half (-0.5in), so a cover's
# shaded elements bleed most of the way to the physical page edge while
# still leaving a 0.5in buffer — true edge-to-edge bleed would put text
# uncomfortably at the literal page edge (a real print-cutoff risk too).
# Report-only: Policy and Document stay fully inset within the margins.
BLEED_TWIPS = -720


def set_style_font_color(doc, style_name, color=None, bold=None, size=None):
    style = doc.styles[style_name]
    style.font.name = FONT
    rpr = style.element.get_or_add_rPr()
    rFonts = rpr.find(qn('w:rFonts'))
    if rFonts is None:
        rFonts = OxmlElement('w:rFonts')
        rpr.append(rFonts)
    for attr in ('w:ascii', 'w:hAnsi', 'w:eastAsia', 'w:cs'):
        rFonts.set(qn(attr), FONT)
    # Pandoc's default styles carry theme-font attributes (w:asciiTheme etc.)
    # on the same rFonts element, and per ECMA-376 §17.3.2.26 theme
    # attributes OVERRIDE the literal ones when both are present — leaving
    # them in place means the style silently renders in the document theme's
    # font (Aptos Display in Pandoc 3.x), not Calibri. Strip them so the
    # literal values actually win.
    for attr in ('w:asciiTheme', 'w:hAnsiTheme', 'w:eastAsiaTheme', 'w:cstheme'):
        if rFonts.get(qn(attr)) is not None:
            del rFonts.attrib[qn(attr)]
    if color is not None:
        style.font.color.rgb = color
    if bold is not None:
        style.font.bold = bold
    if size is not None:
        style.font.size = size


def _apply_shading_and_indent(pPr, shading_hex, pad_h_twips):
    if shading_hex is not None:
        shd = OxmlElement('w:shd')
        shd.set(qn('w:val'), 'clear')
        shd.set(qn('w:fill'), shading_hex)
        pPr.append(shd)
    if pad_h_twips:
        ind = OxmlElement('w:ind')
        ind.set(qn('w:left'), str(pad_h_twips))
        ind.set(qn('w:right'), str(pad_h_twips))
        pPr.append(ind)


def style_title(doc, size, text_color, bold=True, space_before=Pt(18), space_after=Pt(16),
                 shading_hex=None, pad_h_twips=0, alignment=None):
    """Title style. With shading_hex=None (policy/document): plain colored
    text, no box. With shading_hex set (report): a colored panel —
    paragraph shading covers the paragraph's own space_before/space_after
    too, so those act as the panel's internal top/bottom padding, not
    just inter-paragraph gaps. pad_h_twips (report only) bleeds the panel
    past the page margin — see BLEED_TWIPS.

    alignment=None leaves Pandoc's own default (center); pass 0 to
    left-align (document, report)."""
    style = doc.styles['Title']
    pPr = style.element.get_or_add_pPr()
    _apply_shading_and_indent(pPr, shading_hex, pad_h_twips)
    if alignment is not None:
        style.paragraph_format.alignment = alignment
    style.font.color.rgb = text_color
    style.font.size = size
    style.font.bold = bold
    style.paragraph_format.space_before = space_before
    style.paragraph_format.space_after = space_after
    style.paragraph_format.line_spacing = 1.15


def add_left_rule(doc, style_name, color_hex, size_eighths_pt=24, space_pt=10):
    """A colored vertical rule along the paragraph's left edge — Document's
    distinguishing accent, a classic 'quote bar' beside a left-aligned
    headline. w:pBdr's own w:space attribute is in points (not twips,
    unlike almost everything else in this file) — that's the gap between
    the rule and the text, no separate indent needed for it."""
    style = doc.styles[style_name]
    pPr = style.element.get_or_add_pPr()
    pBdr = OxmlElement('w:pBdr')
    left = OxmlElement('w:left')
    left.set(qn('w:val'), 'single')
    left.set(qn('w:sz'), str(size_eighths_pt))
    left.set(qn('w:space'), str(space_pt))
    left.set(qn('w:color'), color_hex)
    pBdr.append(left)
    pPr.append(pBdr)


def style_meta_line(doc, style_name, size, text_color, space_before=Pt(0), space_after=Pt(2),
                     alignment=None, pad_h_twips=None):
    """Author/Date: plain text below the title, color/size/weight/
    alignment/indent. Shading is left to inherit from Title automatically
    (Author/Date are basedOn Title in Pandoc's default reference.docx) —
    that part of the cascade holds up fine. Indent and alignment are NOT
    relied on to cascade the same way: rendered output showed Author/Date
    sitting flush at a different left position than Title's bled/indented
    text, so Pandoc's default Author/Date styles evidently carry their
    own direct w:ind/w:jc that wins over an inherited one. Pass both
    explicitly wherever Title isn't the plain default (no indent, center)."""
    style = doc.styles[style_name]
    if pad_h_twips is not None:
        pPr = style.element.get_or_add_pPr()
        ind = OxmlElement('w:ind')
        ind.set(qn('w:left'), str(pad_h_twips))
        ind.set(qn('w:right'), str(pad_h_twips))
        pPr.append(ind)
    if alignment is not None:
        style.paragraph_format.alignment = alignment
    style.font.color.rgb = text_color
    style.font.size = size
    style.font.bold = False
    style.paragraph_format.space_before = space_before
    style.paragraph_format.space_after = space_after


def set_header(header_obj, logo_png, logo_height, alignment=1, shading_hex=None,
                space_before=Pt(0), space_after=Pt(0), pad_h_twips=0, width=None):
    """width, if given, stretches the image to an explicit width instead
    of letting it scale proportionally from logo_height — used for the
    report cover's masthead art, which needs to span the full bled panel
    width regardless of its own source aspect ratio."""
    header_obj.is_linked_to_previous = False
    para = header_obj.paragraphs[0]
    pPr = para._p.get_or_add_pPr()
    _apply_shading_and_indent(pPr, shading_hex, pad_h_twips)
    para.alignment = alignment
    para.paragraph_format.space_before = space_before
    para.paragraph_format.space_after = space_after
    run = para.add_run()
    if width is not None:
        run.add_picture(str(logo_png), height=logo_height, width=width)
    else:
        run.add_picture(str(logo_png), height=logo_height)
    return para


def _write_page_field(footer_para):
    footer_para.alignment = 1  # center
    footer_para.text = ""
    run = footer_para.add_run()
    run.font.name = FONT
    run.font.size = Pt(9)
    run.font.color.rgb = GRAY
    fld_begin = OxmlElement('w:fldChar')
    fld_begin.set(qn('w:fldCharType'), 'begin')
    instr = OxmlElement('w:instrText')
    instr.set(qn('xml:space'), 'preserve')
    instr.text = "PAGE"
    fld_end = OxmlElement('w:fldChar')
    fld_end.set(qn('w:fldCharType'), 'end')
    r_element = run._r
    r_element.append(fld_begin)
    r_element.append(instr)
    r_element.append(fld_end)


def add_footer_page_field(section, suppress_first_page=True):
    """Centered page number. suppress_first_page=True (policy/document/
    report): no number on page 1, always the title/cover page. False
    (template): number on every page, since a template has no separate
    'cover' — page 1 is just its first page of real content.

    The XML this produces is spec-correct (titlePg set when suppressing,
    a distinct empty w:type="first" footer, a separate w:type="default"
    footer carrying the PAGE field) and Word/Google Docs honor it exactly
    as intended. LibreOffice 26.2 headless does not: verified with an
    isolated minimal docx that as soon as ANY header is present — even one
    identically defined for first-page and default, with no other
    asymmetry at all — LO leaks the default footer's page number onto
    page 1 regardless. Same category of LO-headless-only limitation as
    the TOC-field-population issue noted below (a rendering tool gap, not
    a document defect) — Word and Google Docs are the real targets."""
    section.different_first_page_header_footer = True
    section.first_page_footer.is_linked_to_previous = False
    if suppress_first_page:
        section.first_page_footer.paragraphs[0].text = ""
    else:
        _write_page_field(section.first_page_footer.paragraphs[0])

    section.footer.is_linked_to_previous = False
    _write_page_field(section.footer.paragraphs[0])


def base_document():
    """Build the shared base every reference doc starts from: Pandoc's
    own default reference.docx, with page size, fonts/heading colors, and
    the update-fields flag applied. Each track then layers its own
    margins, title-page treatment, header, and footer on top of this —
    those vary too much between tracks (cover-only big logo vs. no cover
    at all vs. full-bleed panel) to usefully share here."""
    base_path = Path(tempfile.mkdtemp()) / "default-reference.docx"
    subprocess.run(
        ["pandoc", "-o", str(base_path), "--print-default-data-file", "reference.docx"],
        check=True,
    )
    doc = Document(str(base_path))

    # Pandoc's default reference.docx doesn't set page size explicitly
    # (python-docx reads it back as None) — pin it so each track's fixed
    # vertical-positioning math is against a known page height, not
    # whatever the rendering application happens to default to. Margins
    # are set per-track, not here.
    section = doc.sections[0]
    section.page_width = Inches(8.5)
    section.page_height = Inches(11)
    section.left_margin = Inches(1)
    section.right_margin = Inches(1)
    section.bottom_margin = Inches(1)

    set_style_font_color(doc, 'Normal')
    set_style_font_color(doc, 'Heading 1', color=ACCENT, bold=True, size=Pt(18))
    set_style_font_color(doc, 'Heading 2', color=ACCENT, bold=True, size=Pt(14))
    set_style_font_color(doc, 'Heading 3', color=ACCENT, bold=True, size=Pt(12))
    set_style_font_color(doc, 'TOC Heading', color=ACCENT, bold=True, size=Pt(18))
    # Title/Author/Date need the same Calibri treatment: style_title and
    # style_meta_line set color/size/shading but never touch the font
    # name, so without these calls the three title-page styles keep ONLY
    # Pandoc's theme-font attributes and render in the theme font instead
    # of Calibri.
    set_style_font_color(doc, 'Title')
    set_style_font_color(doc, 'Author')
    set_style_font_color(doc, 'Date')

    # Page break before TOC Heading — separates the title/cover page from
    # the TOC page. Policy/document/report pass --toc; templates don't
    # (see build_template_reference), so this only ever fires for the
    # other three.
    doc.styles['TOC Heading'].paragraph_format.page_break_before = True

    # Tell any compliant consumer (Word, in particular) to refresh all
    # fields — including the TOC field — the moment the document is
    # opened, so a reader never has to manually press F9. This does NOT
    # fix LibreOffice's headless PDF export, which was confirmed (by
    # testing both this flag and an export-filter option) to leave the
    # TOC field unpopulated regardless — a rendering-tool limitation, not
    # a document defect. Word honors this flag per spec, and Google Docs
    # independently converts the field to its own live, auto-refreshing
    # TOC object at import time either way.
    update_fields = OxmlElement('w:updateFields')
    update_fields.set(qn('w:val'), 'true')
    doc.settings.element.insert(0, update_fields)

    return doc, section


def render(doc, preview_content, output, toc=True):
    with tempfile.TemporaryDirectory() as tmp:
        # Pandoc's own default reference.docx body is just a swatch of
        # literal style-name placeholders ("Heading 1", "Body Text.", ...)
        # — useless for judging what a real document actually looks like.
        # Rendering a realistic preview document through this styled base
        # (via --reference-doc) bakes real, meaningful demo content into
        # the final reference doc while keeping every style, header, and
        # footer intact — pandoc copies those through unchanged from
        # whatever --reference-doc it's given.
        styled_base_path = Path(tmp) / "styled-base.docx"
        doc.save(str(styled_base_path))
        cmd = ["pandoc", str(preview_content), f"--reference-doc={styled_base_path}"]
        if toc:
            cmd.append("--toc")
        cmd += ["-o", str(output)]
        subprocess.run(cmd, check=True)
        print(f"saved {output}")


def build_policy_reference():
    """Policy: restrained, centered, single-focused — the one track
    tuned specifically for compliance-grade policy documents (SOC 2 /
    ISO 27001 and similar), not shared with any other genre. A much
    larger logo (POLICY_COVER_LOGO_HEIGHT) anchors the cover; Title sits
    at the page's true vertical center below it; Author/Date sit low on
    the page, not immediately under the title — the three read as three
    distinct zones (mark, title, metadata) rather than one tight cluster.

    Interior pages (2+) drop back to the small logo — the cover's scale
    is a title-page device, not a running brand mark."""
    doc, section = base_document()
    section.header_distance = Inches(0.5)
    section.top_margin = Inches(2.75)
    add_footer_page_field(section, suppress_first_page=True)

    # Title.space_before targets the page's true vertical center (11in
    # page, center at 5.5in/396pt from the top) for a 1-line title: work
    # backward from top_margin (198pt) plus half this style's own line
    # height. Author.space_before is tuned against the 2-line WRAPPED
    # title stress test ("Remote Access and Bring-Your-Own-Device (BYOD)
    # Security Policy") so the metadata block still lands low on the page
    # without overflowing onto a spurious page 2 — a 1-line title gets
    # more breathing room above its metadata than a 2-line one does, the
    # same accepted asymmetry as previous iterations of this file (no
    # per-document conditional logic is reachable at the paragraph-style
    # level, so one number has to serve every title length).
    style_title(doc, size=Pt(24), text_color=ACCENT, space_before=Pt(184), space_after=Pt(16))
    style_meta_line(doc, 'Author', size=Pt(11), text_color=GRAY, space_before=Pt(220), space_after=Pt(2))
    style_meta_line(doc, 'Date', size=Pt(10), text_color=GRAY, space_after=Pt(0))

    set_header(section.first_page_header, LOGO_STACKED_BLACK, POLICY_COVER_LOGO_HEIGHT, alignment=1)
    set_header(section.header, LOGO_STACKED_BLACK, LOGO_HEIGHT, alignment=1)

    render(doc, PREVIEW_CONTENT_POLICY, POLICY_OUTPUT)


def build_document_reference():
    """Document: living operational/legal records (runbooks, the legal
    index, and similar) that need a real title page but aren't
    compliance policy and aren't a periodic report. Left-aligned with a
    thin accent rule beside the title — a classic 'quote bar' headline
    treatment — distinguishes it from Policy's centered restraint without
    reaching for Report's color and imagery. Small corner logo, identical
    on every page — there's no dramatic cover-only scale-up here, so
    first-page/default don't need to differ."""
    doc, section = base_document()
    section.header_distance = Inches(0.5)
    section.top_margin = Inches(1.6)
    add_footer_page_field(section, suppress_first_page=True)

    style_title(doc, size=Pt(26), text_color=ACCENT, space_before=Pt(48), space_after=Pt(18), alignment=0)
    add_left_rule(doc, 'Title', color_hex=ACCENT_HEX, size_eighths_pt=24, space_pt=10)
    style_meta_line(doc, 'Author', size=Pt(11), text_color=GRAY, space_before=Pt(6), space_after=Pt(2), alignment=0)
    style_meta_line(doc, 'Date', size=Pt(10), text_color=GRAY, space_after=Pt(0), alignment=0)

    for header_obj in (section.first_page_header, section.header):
        set_header(header_obj, LOGO_HORIZONTAL_BLACK, LOGO_HEIGHT, alignment=0)

    render(doc, PREVIEW_CONTENT_DOCUMENT, DOCUMENT_OUTPUT)


def build_report_reference():
    """Report: a full-bleed graphic cover — the "annual report / pitch
    deck" genre Policy deliberately avoids. Cover header (page 1 only) is
    ONE image spanning the masthead: a low-poly violet mosaic (see
    generate-cover-art.py) with the white logo already composited onto
    it, rather than a plain color band — an earlier version was just the
    logo on a flat COVER_HEX fill with two small watermark-style copies
    of the icon, which read as "a large block of purple," not a graphic
    cover, per direct feedback. Title is the cover's actual hero (left-
    aligned, large, bold) with Author/Date sitting low on the page below
    it. Every cover element bleeds most of the way to the physical page
    edge via BLEED_TWIPS. Interior pages (2+) drop back to the same small
    black header every other track uses — the graphic treatment is
    cover-only, not carried through the whole report."""
    doc, section = base_document()
    # top_margin is tuned to where the header's own content actually ends
    # (measured empirically, not computed from the nominal spacing sum —
    # see style_title's space_before note below for why the two diverge).
    # header block: header_distance 0.2in + art (space_before 8pt +
    # REPORT_ART_HEIGHT + space_after 10pt) renders to about 3.0in in
    # practice.
    section.header_distance = Inches(0.2)
    section.top_margin = Inches(3.0)
    add_footer_page_field(section, suppress_first_page=True)

    # Title.space_before is kept SMALL and deliberately treated as an
    # unshaded gap, not internal panel padding: unlike every other
    # space_before/space_after in this file, measuring the rendered
    # output showed shading does NOT extend through space_before on a
    # section's first body paragraph specifically (it does between two
    # already-shaded paragraphs, e.g. within the header above) — a real
    # LibreOffice/OOXML-interaction quirk, not something fixable by
    # reordering the shading/spacing XML. Fighting it to force a
    # perfectly seamless header-to-title transition wasn't worth it; a
    # small visible seam between the two blocks reads fine on its own.
    style_title(
        doc, size=Pt(36), text_color=WHITE, space_before=Pt(16), space_after=Pt(20),
        shading_hex=COVER_HEX, pad_h_twips=BLEED_TWIPS, alignment=0,
    )
    style_meta_line(
        doc, 'Author', size=Pt(13), text_color=WHITE, space_before=Pt(280), space_after=Pt(4),
        alignment=0, pad_h_twips=BLEED_TWIPS,
    )
    # Date is the last paragraph in the shaded panel — its space_after is
    # the panel's bottom padding, same role Title's space_after plays.
    style_meta_line(
        doc, 'Date', size=Pt(11), text_color=COVER_LIGHT, space_after=Pt(48),
        alignment=0, pad_h_twips=BLEED_TWIPS,
    )

    # BLEED_TWIPS makes the panel span page_width - 2*(1in - 0.5in) = 7.5in;
    # the mosaic's own aspect ratio (16:9) doesn't match that at
    # REPORT_ART_HEIGHT, so width is set explicitly to stretch it to fill
    # the panel edge-to-edge rather than leaving it narrower than the
    # bled title panel below.
    set_header(
        section.first_page_header, COVER_ART, REPORT_ART_HEIGHT, alignment=1,
        shading_hex=COVER_HEX, space_before=Pt(8), space_after=Pt(10), pad_h_twips=BLEED_TWIPS,
        width=Inches(7.5),
    )
    set_header(section.header, LOGO_STACKED_BLACK, LOGO_HEIGHT, alignment=1)

    render(doc, PREVIEW_CONTENT_REPORT, REPORT_OUTPUT)


def build_template_reference():
    """Template: blank fillable forms never trigger Pandoc's title-block
    (no YAML frontmatter), so Title/Author/Date styles here are simply
    unused — nothing to design. Just a small consistent header and,
    unlike the other three tracks, page numbers on every page including
    page 1: a template has no separate 'cover', page 1 is just its first
    page of real content. No --toc either, matching existing behavior."""
    doc, section = base_document()
    section.header_distance = Inches(0.4)
    section.top_margin = Inches(1)
    add_footer_page_field(section, suppress_first_page=False)

    for header_obj in (section.first_page_header, section.header):
        set_header(header_obj, LOGO_STACKED_BLACK, LOGO_HEIGHT, alignment=1)

    render(doc, PREVIEW_CONTENT_TEMPLATE, TEMPLATE_OUTPUT, toc=False)


def main():
    build_policy_reference()
    build_document_reference()
    build_report_reference()
    build_template_reference()


if __name__ == "__main__":
    main()
